---
name: Helm lint

#
# Documentation:
# https://help.github.com/en/articles/workflow-syntax-for-github-actions
#

permissions: read-all

on: [push, pull_request]

jobs:
  build:
    name: Run helm lint over the chart
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        with:
          persist-credentials: false

      - name: Setup helm
        uses: azure/setup-helm@5119fcb9089d432beecbf79bb2c7915207344b78 # v4
        with:
          version: 'v3.14.0'

      - name: Run make helmlint
        run: |
          make helm-lint
